import("./Helper")

desc "Generate the common documentation"
lane :export do |options|
  output_dir = "../mobile_sdk_documentation_published/common/"
  comment = options[:comment]
  generateCommonDocs(output_dir)
  stagingDocs(comment)
end

def generateCommonDocs(output_dir)
  absolute_path = absolute_path(output_dir)
  sh "bundle exec middleman build --build-dir=\"#{absolute_path}\""
end

def stagingDocs(comment)
  UI.message "commit with comment #{comment} and push"
  sh "../mobile_sdk_documentation_published/publish \"#{comment}\""
end
